name: Rust

on:
  push:
    branches: [ "ci_test" ]
  pull_request:
    branches: [ "ci_test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
      with:
        node-version: 16.x
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
        
    - name: wasm-bindgen-action
      uses: jetli/wasm-bindgen-action@v0.1.0

    - name: Build
      run: npm i wasm-opt -g;npm install --global vsce;BUILDSH_RELEASE=1 ./build.sh package
    - uses: actions/upload-artifact@v3
      with:
        name: vsix
        path: icie/target/evscode/icie*.vsix
    
